server:
  port: 8808
spring:
  application:
    name: charon
# for develop
  thymeleaf:
    cache: false
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true